export const SUPERMARKETS: any = [
  {
    id: 1,
    name: 'CONSUM',
    title: 'CONSUM',
    src: '../../../assets/images/logo-consum.png',
    srcWidth: '30px',
    variable: 'consumProducts',
    background: '#ff9800',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 2,
    name: 'MERCADONA',
    title: '',
    src: '../../../assets/images/logo-mercadona.svg',
    srcWidth: 'fit-content',
    variable: 'externalProducts',
    background: '#a1e3c8',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 3,
    name: 'CARREFOUR',
    title: '',
    src: '../../../assets/images/loco-carre.svg',
    srcWidth: '12rem',
    variable: 'carrefourProducts',
    background: '#a1b9e3',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 4,
    name: 'ALDI',
    title: 'ALDI',
    src: '../../../assets/images/logo-aldi.svg',
    srcWidth: '',
    variable: 'aldiProducts',
    background: '#40c8f2',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 5,
    name: 'DIA',
    title: 'DIA',
    src: '../../../assets/images/logo-dia.png',
    srcWidth: '',
    variable: 'diaProducts',
    background: '#ce1c19',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 6,
    name: 'MASYMAS',
    title: 'MASYMAS',
    src: '../../../assets/images/masymas-logo.png',
    srcWidth: '',
    variable: 'masymasProducts',
    background: '#0d5e43',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 7,
    name: 'ALCAMPO',
    title: 'ALCAMPO',
    src: '../../../assets/images/alcampo-logo.png',
    srcWidth: '',
    variable: 'alcampoProducts',
    background: '#c49493',
    opened: false,
    filter: 'OFF',
  },
];
