export const SUPERMARKETS: any = [
  {
    id: 1,
    name: 'CONSUM',
    title: 'CONSUM',
    src: '../../../assets/images/logo-consum.png',
    srcWidth: '30px',
    variable: 'consumProducts',
    background: '#ff9800',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 2,
    name: 'MERCADONA',
    title: '',
    src: '../../../assets/images/logo-mercadona.svg',
    srcWidth: 'fit-content',
    variable: 'externalProducts',
    background: '#a1e3c8',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 3,
    name: 'CARREFOUR',
    title: '',
    src: '../../../assets/images/loco-carre.svg',
    srcWidth: '12rem',
    variable: 'carrefourProducts',
    background: '#a1b9e3',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 4,
    name: 'ALDI',
    title: 'ALDI',
    src: '../../../assets/images/logo-aldi.svg',
    srcWidth: '',
    variable: 'aldiProducts',
    background: '#40c8f2',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 5,
    name: 'DIA',
    title: 'DIA',
    src: '../../../assets/images/logo-dia.png',
    srcWidth: '',
    variable: 'diaProducts',
    background: '#ce1c19',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 6,
    name: 'MASYMAS',
    title: 'MASYMAS',
    src: '../../../assets/images/masymas-logo.png',
    srcWidth: '',
    variable: 'masymasProducts',
    background: '#0d5e43',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 7,
    name: 'ALCAMPO',
    title: 'ALCAMPO',
    src: '../../../assets/images/alcampo-logo.png',
    srcWidth: '',
    variable: 'alcampoProducts',
    background: '#c49493',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 8,
    name: 'GADIS',
    title: 'GADIS',
    src: '../../../assets/images/gadis-logo.jpeg',
    srcWidth: '',
    variable: 'gadisProducts',
    background: '#552a19',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 9,
    name: 'ECI',
    title: 'ECI',
    src: '../../../assets/images/eci-logo.png',
    srcWidth: '',
    variable: 'eciProducts',
    background: '#016754',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 10,
    name: 'HIPERCOR',
    title: 'HIPERCOR',
    src: '../../../assets/images/hipercor-logo.png',
    srcWidth: '',
    variable: 'hipercorProducts',
    background: '#00337a',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 11,
    name: 'EROSKI',
    title: 'EROSKI',
    src: '../../../assets/images/eroski-logo.svg',
    srcWidth: '',
    variable: 'eroskiProducts',
    background: '#184586',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 12,
    name: 'LIDL',
    title: 'LIDL',
    src: '../../../assets/images/lidl-logo.svg',
    srcWidth: '',
    variable: 'lidlProducts',
    background: '#0050aa',
    opened: false,
    filter: 'OFF',
  },
  {
    id: 13,
    name: 'HIPERDINO',
    title: 'HIPERDINO',
    src: '../../../assets/images/hiperdino-logo.png',
    srcWidth: '',
    variable: 'hiperdinoProducts',
    background: '#016941',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 14,
    name: 'CONDIS',
    title: 'CONDIS',
    src: '../../../assets/images/condis-logo.jpeg',
    srcWidth: '',
    variable: 'condisProducts',
    background: '#e62b37',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 15,
    name: 'BONPREU',
    title: 'BONPREU',
    src: '../../../assets/images/bonpreu-logo.png',
    srcWidth: '',
    variable: 'bonpreuProducts',
    background: '#f6c046',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 16,
    name: 'AHORRAMAS',
    title: 'AHORRAMAS',
    src: '../../../assets/images/ahorramas-logo.png',
    srcWidth: '',
    variable: 'ahorramasProducts',
    background: '#ffc700',
    opened: false,
    filter: 'OFF',
  },

  {
    id: 17,
    name: 'BONAREA',
    title: 'BONAREA',
    src: '../../../assets/images/bonarea-logo.png',
    srcWidth: '',
    variable: 'bonareaProducts',
    background: '#ff7900',
    opened: false,
    filter: 'OFF',
  },
];
